version: '3'
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.playwright
    volumes:
      - ./:/app/
    command: npx playwright test
    environment:
      - DEBUG=pw:webserver
  update-snapshots:
    build:
      context: .
      dockerfile: Dockerfile.playwright
    volumes:
      - ./:/app/
    command: npx playwright test --update-snapshots
