version: '3'
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.playwright
    command: npx playwright test
  update-snapshots:
    build:
      context: .
      dockerfile: Dockerfile.playwright
    command: npx playwright test --update-snapshots
